// window variables
export const WINDOW_RESIZED = "WINDOW_RESIZED";
// update tick
export const UPDATE_TICK = "UPDATE_TICK";
// authentiction
export const AUTHENTICATION__SET_FINGERPRINT =
  "AUTHENTICATION__SET_FINGERPRINT";
export const AUTHENTICATION__SET_TOKEN = "AUTHENTICATION__SET_TOKEN";

export default [
  WINDOW_RESIZED,
  UPDATE_TICK,
  AUTHENTICATION__SET_FINGERPRINT,
  AUTHENTICATION__SET_TOKEN,
];
